### ISSUE TITLE
Extension tells me projects do not exist.

### ISSUE THREAD

**Issue by Kuffs2205** [luminous-software/start-page-plus#38] opened 2020-06-02 11:00 UTC
### Installed product versions
- Visual Studio: 2019
- This extension:1.0

### Description
I keep getting a dialog when choosing a shortcut from the start page
---------------------------
Warning
---------------------------
Can't find '"B:\Dev\Windows Personal\TestProject\TestProject.sln"'
---------------------------
OK   
---------------------------

Projects on my C drive seem to load ok. None from my B drive can be found. This is only since the 1.0 update

### Steps to recreate
1. Press a shortcut

### Current behavior
Telling me that a project doesn't exist when it does

### Expected behavior
Load the project

**Comment by Kuffs2205** [comment] 2020-06-02 11:07
Extra Info:

Pressing the shortcut button gives the error. Right clicking and choosing "Open in VS" works.

**Comment by yannduran** [comment] 2020-06-03 02:16
Thanks for the heads up! I initially had some trouble with this, but I thought I had sorted it.

1. This is only for projects/solutions with a space in the name?
2. Do you have any projects/solutions on your `C:` drive that have a space? If so, do they open?
3. Is it only projects/solutions on your `B:` drive that have a space that won't open?
4. What happens if you type `"B:\Dev\Windows Personal\TestProject\TestProject.sln"` into a command prompt? (include the quotes)
5. Is your `B:` drive any different from your `C:` drive? Is it a USB drive? Or mapped to a network share?

Thanks!

**Comment by Kuffs2205** [comment] 2020-06-03 10:43
1. Yes It does seem to only be for projects with a space in the path. (I thought I checked this yesterday but obviously not well enough)
2. Only the ones without a space open.
3. No, All projects with a space regardless of location.
4. The project opens.
5. Its a standard SATA SSD drive.  I map to B to keep my data drive separate from my other drives.

I perhaps wasn't clear with my comment yesterday either.  Pressing the shortcut button on the start page+ for a project with a space in it tells me it cannot be found. Right clicking the same shortcut and choosing "Open In VS" opens it just fine. I guess they have slightly different open methods?

**Comment by yannduran** [comment] 2020-06-03 11:43
I've confirmed that this is the problem that I thought I had solved. I don't know how that got through, because I was using a test solution/project/folder to test all possibilities of names with spaces.

I know where to look, and I should have a fix soon.

**Comment by yannduran** [comment] 2020-06-09 01:15
This issue has been fixed and will be in *v1.0.1*.

**Closed by yannduran** 2020-06-09 01:15 UTC
Labels: bug
