### ISSUE TITLE
StartPage+ doesn't open at startup

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus#4] opened 2019-09-24 10:30 UTC
### Installed product versions
- Visual Studio: 2019 16.3
- This extension: 0.12.1

### Description

StartPage+ doesn't open at startup and crashes VS2019 when manually running it (but when I run devenv.exe inside Windbg, the page shows up).

### Steps to recreate
1. Install VS2019 16.3
2. Install StartPage+
3. restart

### Current behavior

only empty environment hows up, clicking on "View"->"Start Page+" causes VS to crash

### Expected behavior

Start Page+ hows up fine after start.

**Comment by MagicAndre1981** [comment] 2019-09-24 11:34
now it gets wired. After I was only able to use Start Page+ in Windbg, I can now run it fine without windbg  🤔  🤷‍♂️

**Comment by yannduran** [comment] 2019-09-25 05:58
Maybe your version was automatically updated to a later version. The current version is v0.12.1.4 - there is still an issue of the window not opening if you close it that I haven't had time to find out why yet.

Start Page+ should never have crashed VS though. I use it myself and that's never happened to me. Maybe there was something else affecting your VS Preview version. Who knows lol. I'm glad it's working for you now.

Can I close this issue now?

**Comment by MagicAndre1981** [comment] 2019-09-25 06:28
this was a complete fresh VS2019 16.3 final install without any 3rd party addons. I also disabled automatic VS update and extension update installation and installed StartPage+ from extension UI.

Eventlog shows NullreferenceException while loading Recent Items:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at StartPagePlus.UI.Services.RecentItemDataService.GetItems()
   at StartPagePlus.UI.ViewModels.RecentItemsViewModel.ExecuteRefresh()
   at StartPagePlus.UI.Views.RecentItemsView..ctor()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, Boolean)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Activator.CreateInstance(System.Type, System.Object[])
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(System.Type, System.Object[])
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstance(System.Type, System.Object[])
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(System.Object[])
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(System.Xaml.XamlType, System.Object[])
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(System.Xaml.XamlType, System.Object[])
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(MS.Internal.Xaml.Context.ObjectWriterContext)
   at System.Xaml.XamlObjectWriter.WriteEndObject()
   at System.Xaml.XamlWriter.WriteNode(System.Xaml.XamlReader)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlReader, System.Xaml.XamlObjectWriter)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlObjectWriter)
   at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(System.Windows.DependencyObject, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector, System.Collections.Generic.List`1<System.Windows.DependencyObject>, System.Windows.UncommonField`1<System.Collections.Hashtable>)
   at System.Windows.FrameworkTemplate.LoadContent(System.Windows.DependencyObject, System.Collections.Generic.List`1<System.Windows.DependencyObject>)
   at System.Windows.StyleHelper.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, System.Windows.FrameworkElementFactory, Int32, System.Collections.Specialized.HybridDictionary, System.Windows.FrameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.FrameworkElement)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Controls.Primitives.UniformGrid.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


```

**Comment by MagicAndre1981** [comment] 2019-09-25 07:38
> - there is still an issue of **the window not opening if you close it** that I haven't had time to find out why yet.

this works fine for me in this fresh 16.3 install. I can close StartPage+ and reopen it when I want it. No issue for me.

**Comment by yannduran** [comment] 2019-09-26 07:59
Thanks for that followup André.

`StartPagePlus.UI.Services.RecentItemDataService.GetItems()` shows me where the problem you had is. It's possible that this method fails for some reason (and of course it shouldn't FAIL, I thought I had a try/catch around it - I'll look into that). It's possible that an exception could be thrown in a band new install when there aren't any _recent items_ yet, I hadn't thought of that - I'll look into that as well.

Thanks for also letting me know that you can close and open Start Page+ without a problem, I stopped trying because it was a pain to have to restart VS to be able to get it back again. I'd certainly like to be able to cross that one off the list, though to be honest I couldn't figure out why it was doing it in the first place, which is why I put it off until _later_.

**Comment by MagicAndre1981** [comment] 2019-09-26 08:24
> `StartPagePlus.UI.Services.RecentItemDataService.GetItems()` shows me where the problem you had is. It's possible that this method fails for some reason (and of course it shouldn't FAIL, I thought I had a try/catch around it - I'll look into that). It's possible that an exception could be thrown in a band new install when there aren't any _recent items_ yet, I hadn't thought of that - I'll look into that as well.

it was wired because I got a messagebox but only strange error code and after clicking ok, VS crashed.

But now it works. Maybe OpenSubKey failed which is not wrapped around try/catch

**Comment by MagicAndre1981** [comment] 2019-09-26 19:33
ok, someone [already made a PR for the NullRefException issue](https://github.com/luminous-software/start-page-plus/pull/9)

**Comment by sevanmarc** [comment] 2019-09-27 07:27
That was me. Yes it only happened on a new VS preview install that had never been run before, with no recent items. I was actually trying to find some better colours, the exception fix was just something I had to get past first!

**Comment by yannduran** [comment] 2019-09-27 13:44
Thank Marc for that! I'll try to get that into Preview 2.

**Comment by MagicAndre1981** [comment] 2019-10-04 17:35
as it works now fine, I'll close the issue.

**Comment by Dean-NC** [comment] 2020-06-20 00:12
I'm guessing when you implement the auto-close when opening a solution feature, you will make it re-open when re-starting VS?  Right now, if we close it, then it won't automatically show when re-starting VS.

**Comment by yannduran** [comment] 2020-06-20 01:24
At the moment that has more to do with the way Microsoft persists (or in this case doesn't persist) certain types of tool windows docked in the document well than it has to do with _Start Page+_ itself. 

The _Start Page+_ window is **just a tool window** like any other tool window, but tool windows that are docked in the document well don't get properly persisted and Microsoft claim that this is **_by design_**. This includes tool windows like _Git history_, _browser windows_ etc, . About the only exception seems to be the _Output Window_. 

I've left off writing code to explicitly do it, hoping that they'll **fix** it in an imminent update while I've had more urgent features to address. 

[@stimpy77](https://github.com/stimpy77)/aka @JonDavis-AZED submitted a [pull request](https://github.com/luminous-software/start-page-plus/pull/33) a while back that I haven't had the chance to integrate yet. It should be in [v1.1](https://github.com/luminous-software/start-page-plus/milestone/6), due by the end of the month.

I use _Azure DevOps_ as my main repository, and only upload the final code to _GitHub_ for each new release, so I don't think I can directly handle a pull request from _GitHub_ into _Azure DevOps_. If anyone knows how to do this, please let me know.

**Comment by Dean-NC** [comment] 2020-06-20 01:56
@yannduran Ahh, I see. Thanks for the response.  There's no doubt MS has no interest in auto-showing a "tool window", but maybe there's a way to get it done.

**Comment by yannduran** [comment] 2021-04-24 00:41
Hey guys, is this still a problem for you?

**Comment by MagicAndre1981** [comment] 2021-04-24 12:04
If it doesn't show I need to click once in Menu to open it. Next time StartPage++ starts fine

**Closed** 2021-04-24 12:04 UTC
