### ISSUE TITLE
Missing prerequisites for VS 2017

### ISSUE THREAD

**Issue by kzendra** [luminous-software/start-page-plus#8] opened 2019-09-26 08:32 UTC
![image](https://user-images.githubusercontent.com/14160159/65672103-c5a98880-e048-11e9-8e7b-0feb20bb4f5e.png)

I cant install start page + due to missing prerequisites and I can't find list of prerequisites anywhere

Microsoft Visual Studio Enterprise 2017 
Version 15.9.16
VisualStudio.15.Release/15.9.16+28307.858
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Visual C++ 2017   00369-60000-00001-AA973
Microsoft Visual C++ 2017

AnyStatus   1.0
AnyStatus Detailed Info

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.9.03024.0
Azure Functions and Web Jobs Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.20417.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61906.03120
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.9.30718.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.858
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

**Comment by MagicAndre1981** [comment] 2019-09-26 10:31
this extension is for Visual Studio 2019 to bring a replacement for the missing Start Page and replace the ugly Start Windows of 2019.

**Comment by kzendra** [comment] 2019-09-26 10:38
Then VS2017 should be excluded from: 
Works with
Visual Studio 2017, 2019

https://marketplace.visualstudio.com/items?itemName=YannDuran.StartPagePlus

**Comment by yannduran** [comment] 2019-09-27 13:40
@kzendra I'm sorry about that. André is right, Start Page+ was intended for VS 2019, there's no reason it shouldn't work in VS 2017 as well if I set the manifest prerequisites properly. I'll try to include support for VS 2017 in the next preview.And if I can't I'll do as you say and remove VS 2017 from the target versions.

**Comment by yannduran** [comment] 2019-09-30 13:53
Preview 2 has now been released with a fix for this issue.

Please let me know if you continue to experience any problems. Feel free to re-open this issue.

**Comment by yannduran** [comment] 2019-10-03 14:25
@kzendra are you able to install Start Page+ in VS 2017 successfully now? 

If not, please re-open this issue, and I''l look  into it further.

Thanks!

**Comment by kzendra** [comment] 2019-10-03 15:14
Installed but not working.
Sorry, been a bit bussy

![image](https://user-images.githubusercontent.com/14160159/66139490-d639a000-e600-11e9-9648-dd6084e45474.png)

[ActivityLog.zip](https://github.com/luminous-software/start-page-plus/files/3686769/ActivityLog.zip)

**Comment by MagicAndre1981** [comment] 2019-10-03 15:38
`CreateInstance failed for package [PackageClass]Source: 'mscorlib' Description: Could not load file or assembly 'Microsoft.VisualStudio.Shell.Framework, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.Framework, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Shell.Framework, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'    at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)    at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)    at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)    at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) `

DLl in version 16 not found, common issue for extension developers if they reference NuGet packages for VS SDK and use 16.x packages. VS2017 needs the 15.x nuget versions.

**Comment by yannduran** [comment] 2019-10-04 01:16
D'oh, that sounds like a rookie mistake! Thanks for the heads-up André.

I realise now what I must have done. I verified that it installed in my VS 2017 (which I don't use anymore), but I apparently forgot to make sure that the window actually opened. **groan**

**Comment by yannduran** [comment] 2019-10-11 10:42
This has been fixed, and will be included in Preview 4.

**Closed by yannduran** 2019-10-11 10:42 UTC
